<?php

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            'name' => 'Diego',
            'lastname' => 'Piedra',
            'username' => 'diegojopiedra',
            'email' => 'diegojopiedra@gmail.com',
            'profile_pic' => '49612769_2140747552650371_4553587501893156864_n.jpg',
            'password' => bcrypt('12345678'),
        ]);

        for ($i=0; $i < 200; $i++) { 
            DB::table('users')->insert([
                'name' => $this->randomName(),
                'lastname' => $this->randomLastname(),
                'username' => Str::random(10),
                'email' => Str::random(10).'@gmail.com',
                'password' => bcrypt('1234'),
            ]);
        }
    }

    private function randomName(){
        $names = [
            'Isabella',
            'Daniel',
            'Olivia',
            'David',
            'Alexis',
            'Gabriel',
            'Sofía',
            'Benjamín',
            'Victoria',
            'Samuel',
            'Amelia',
            'Lucas',
            'Alexa',
            'Ángel',
            'Julia',
            'José',
            'Camila',
            'Adrián',
            'Alexandra',
            'Sebastián',
            'Maya',
            'Xavier',
            'Andrea',
            'Juan',
            'Ariana',
            'Luis',
            'María',
            'Diego',
            'Eva',
            'Óliver',
            'Angelina',
            'Carlos',
            'Valeria',
            'Jesús',
            'Natalia',
            'Alex',
            'Isabel',
            'Max',
            'Sara',
            'Alejandro',
            'Liliana',
            'Antonio',
            'Adriana',
            'Miguel',
            'Juliana',
            'Víctor',
            'Gabriela',
            'Joel',
            'Daniela',
            'Santiago',
            'Valentina',
            'Elías',
            'Lila',
            'Iván',
            'Vivian',
            'Óscar',
            'Nora',
            'Leonardo',
            'Ángela',
            'Eduardo',
            'Elena',
            'Alan',
            'Clara',
            'Nicolás',
            'Eliana',
            'Jorge',
            'Alana',
            'Omar',
            'Miranda',
            'Paúl',
            'Amanda',
            'Andrés',
            'Diana',
            'Julián',
            'Ana',
            'Josué',
            'Penélope',
            'Román',
            'Aurora',
            'Fernando',
            'Alexandría',
            'Javier',
            'Lola',
            'Abraham',
            'Alicia',
            'Ricardo',
            'Amaya',
            'Francisco',
            'Alexia',
            'César',
            'Jazmín',
            'Mario',
            'Mariana',
            'Manuel',
            'Alina',
            'Édgar',
            'Lucía',
            'Alexis',
            'Fátima',
            'Israel',
            'Ximena',
            'Mateo',
            'Laura',
            'Héctor',
            'Cecilia',
            'Sergio',
            'Alejandra',
            'Emiliano',
            'Esmeralda',
            'Simón',
            'Verónica',
            'Rafael',
            'Daniella',
            'Martín',
            'Miriam',
            'Marco',
            'Carmen',
            'Roberto',
            'Iris',
            'Pedro',
            'Guadalupe',
            'Emanuel',
            'Selena',
            'Abel',
            'Fernanda',
            'Rubén',
            'Angélica',
            'Fabián',
            'Emilia',
            'Emilio',
            'Lía',
            'Joaquín',
            'Tatiana',
            'Marcos',
            'Mónica',
            'Lorenzo',
            'Carolina',
            'Armando',
            'Jimena',
            'Adán',
            'Dulce',
            'Raúl',
            'Talía',
            'Julio',
            'Estrella',
            'Enrique',
            'Brenda',
            'Gerardo',
            'Lilian',
            'Pablo',
            'Paola',
            'Jaime',
            'Serena',
            'Saúl',
            'Celeste',
            'Esteban',
            'Viviana',
            'Gustavo',
            'Elisa',
            'Rodrigo',
            'Melina',
            'Arturo',
            'Gloria',
            'Mauricio',
            'Claudia',
            'Orlando',
            'Sandra',
            'Hugo',
            'Marisol',
            'Salvador',
            'Asia',
            'Alfredo',
            'Ada',
            'Maximiliano',
            'Rosa',
            'Ramón',
            'Isabela',
            'Ernesto',
            'Regina',
            'Tobías',
            'Elsa',
            'Abram',
            'Perla',
            'Noé',
            'Raquel',
            'Guillermo',
            'Virginia',
            'Ezequiel',
            'Patricia',
            'Lucián',
            'Linda',
            'Alonzo',
            'Marina',
            'Felipe',
            'Leila',
            'Matías',
            'América',
            'Tomás',
            'Mercedes',
            'Jairo',
        ];

        return $names[rand(0, count($names) -1)];
    }

    private function randomLastname(){
        $lastnames = [
            'García',
            'Rodríguez',
            'Martínez',
            'Hernández',
            'López',
            'González',
            'Pérez',
            'Sánchez',
            'Ramírez',
            'Torres',
            'Flores',
            'Rivera',
            'Gómez',
            'Cruz',
            'Reyes',
            'Morales',
            'Gutiérrez',
            'Ortiz',
            'Ramos',
            'Chávez',
            'Mendoza',
            'Ruiz',
            'Álvarez',
            'Castillo',
            'Jiménez',
            'Piedra',
            'Araya',
            'Arias',
        ];

        return $lastnames[rand(0, count($lastnames) -1)];
    }
}
